name: create-release
on:
  push:
    branches:
      - release

jobs:

  release:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/mesh-client' && github.actor != 'dependabot[bot]'
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: clean
        run: |
          git clean -fdx
          find . -type f | xargs chmod g+w

      - name: setup python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: 'pyproject.toml'

      - name: setup poetry
        uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4
        with:
          poetry-version: 2.1.3

      - name: add poetry plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: dist
        run: |
          RELEASE_VERSION="$(poetry version patch | rev | cut -d' ' -f1 | rev)"
          echo "${RELEASE_VERSION}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          if [[ "${RELEASE_VERSION}" == "0.0.0" ]]; then
            echo "${RELEASE_VERSION} = 0.0.0"
            exit 1
          fi
          git tag "${RELEASE_VERSION}"
          RELEASE_VERSION="${RELEASE_VERSION}" make dist

      - name: create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}

      - name: pypi publish
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
