name: merge-develop
on:
  push:
    branches:
      - mm-mesh-1478-move-to-pyproject-toml

jobs:

  coverage:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/mesh-client' && !contains(github.event.head_commit.message, 'tag release version:')
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: print env vars
        run: printenv


#
#  publish:
#    runs-on: ubuntu-latest
#    if: github.repository == 'NHSDigital/mesh-client' && github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, 'tag release version:')
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: clean
#        run: |
#          git clean -fdx
#          find . -type f | xargs chmod g+w
#
#      - name: setup python
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.8"
#
#      - name: setup poetry
#        uses: abatilo/actions-poetry@v2
#        with:
#          poetry-version: 1.5.1
#
#      - name: add poetry plugins
#        run: |
#          poetry self add "poetry-dynamic-versioning[plugin]"
#
#      - name: dist
#        run: |
#          version="v$(poetry version patch | rev | cut -d' ' -f1 | rev)"
#          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
#          git tag $version
#          RELEASE_VERSION=$version" make dist
#          echo "WHEEL=$(find dist -type f -name '*.whl' | xargs basename)" >> $GITHUB_ENV
#          echo "SDIST=$(find dist -type f -name '*.tar.gz' | xargs basename)" >> $GITHUB_ENV
#
#      - name: create release
#        id: create_release
#        uses: actions/create-release@v1
#        continue-on-error: false
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.RELEASE_VERSION }}
#          release_name: ${{ env.RELEASE_VERSION }}
#
#      - name: pypi publish
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          password: ${{ secrets.PYPI_TOKEN }}
#
#      - name: upload wheel
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./dist/${{ env.WHEEL }}
#          asset_name: ${{ env.WHEEL }}
#          asset_content_type: application/zip
#
#      - name: upload sdist
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./dist/${{ env.SDIST }}
#          asset_name: ${{ env.SDIST }}
#          asset_content_type: application/gzip
